export const postsApiUrl = 'https://jsonplaceholder.typicode.com/posts'
export const unsplashApiUrl = 'https://api.unsplash.com'
export const wikipediaApiUrl = 'https://en.wikipedia.org/w/api.php'
export const wikipediaPageUrl = 'https://en.wikipedia.org?curid='
export const unsplashApiKey = 'Client-ID id-zPQ9_VR8YvApMDzNeGhehuSR4eL5Us0Y7gmAnYV8'
export const googleTranslateApiKey = 'AIzaSyCHUCmpR7cT_yDFHC98CZJy2LTms-IwDlM'
